# ---- Simple Robot Gaze Config File ----

# The Simple Robot Gaze component coordinates a Robot's gaze direction.
# This can be done by a) providing (multiple) input sources and by b) prioritizing them.
# For now, the component accepts ROS People messages [1] and ROS RegionOfInterest messsages [2]
# then derives the corresponding robot joint angle configuration using the HLRC [3] library.
# This is accomplished by mapping from the region of interest (faces, ittikoch...) to the camera's
# field of view, robot joint angles respectively.

# TODO: Implement support for ROS TF targets.

# This file must reside in ~/.config/simplerobotgaze.yaml

# In order to stop simple robot gaze from controlling the robot simple send "pause" (string msg) to:
# /srg/arbitrate/toggle
# If you send something other than "pause", simple robot gaze will resume operation.

---

# The priority of input data streams (ROS people msg), the first entry has the highest priority
priorities:
  - /ocvfacerec/ros/people
  - /dlibfacerec/ros/people
  - /movement/people

# Gaze strategy: relative for moving cameras, absolute for fixed setups, corresponds to the priorities
modes:
  - relative
  - relative
  - absolute

# Skip stimulus input for n seconds, e.g., only react every three seconds to a stimulus: 3.0 | no timeout: 0.0
stimulus_timeout:
  - 0.0
  - 0.0
  - 0.0

# What kind of data are you sending in your input stream, corresponds to priorities
datatypes:
  - ros:People
  - ros:Point
  - ros:RegionOfInterest

# Resolution of the source camera image, corresponds to the priorities
resolution:
  - 320x240
  - 320x240
  - 320x240

# Camera field of view horizontal and vertical (in degree), also corresponds to the priorities.
fov:
  - 58.0x45.0
  - 58.0x45.0
  - 58.0x45.0

############################
# TODO ROS TF Integration
# tf:
#  - base
#  - head
#  - hand
############################